spring.application.name=magacin

spring.main.banner-mode=off
logging.level.org.springframework=error
logging.level.fyi.hrvanovicm.magacin=error

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:magacin.db
spring.datasource.username=magacin_app
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.data=classpath:data/data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=8080


spring.docker.compose.skip.in-tests=true
spring.docker.compose.enabled=false

app.auth.jwt.secret-key=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
